import { Metadata } from 'next';
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import UserProvider from './context/UserProvider';

export const metadata: Metadata = {
    title: "Online Learning System",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <UserProvider>
          <Navbar/>
          <main style={{ padding: '2rem' }}>
            {children}
          </main>
        </UserProvider>
        <Footer/>
      </body>
    </html>
  );
}
